### ISSUE TITLE
Not able to convert the file , destination folder is empty, also I want to try for converting js file , is there any option for that?

### ISSUE THREAD

**Issue by meghanagandhi-rs** [AmadeusITGroup/protractor-to-playwright#15]
PS D:\Playrightconversions> npx @amadeus-it-group/protractor-to-playwright@latest --src=D:\Automation_Repository\ui-platform-automation  --dst='D:\conversion' validateAttributeMessage-po.js step
Start migration
Apply 0 transformations
Migration finished

in my case, it is showing 0 migrations, let me know anything which I need to change here?

**Comment by divdavem** [comment]
Hello @meghanagandhi-rs 

Thank you for trying protractor-to-playwright and reporting this issue.

Note that it is currently not valid to just pass the files to convert at the end of the command line as you do with `validateAttributeMessage-po.js`: you should use the `-f` option for that.
However, it is true that your syntax is more intuitive, and I have opened #18 to accept it.

You seem to be using `.js` files (and not `.ts` files). I have just opened #17 to fix some issues with `.js` files that were not handled properly. This could probably fix your issue. 

We will probably do a new release shortly after merging #17 and #18.

**Comment by divdavem** [comment]
@meghanagandhi-rs Now that version 1.1.0 is released, could you please check if the issue is solved?

**Comment by meghanagandhi-rs** [comment]
> I am closing this issue as it is supposed to be fixed in version 1.1.0. Feel free to contact us if needed.

Hey, Hi, I was busy with other High priority task, couldn't find time to check that. give me some time, by tomorrow I will check and update you.

**Comment by meghanagandhi-rs** [comment]
> @meghanagandhi-rs Now that version 1.1.0 is released, could you please check if the issue is solved?

Please send me link for version 1.1.0 unable to tract that.

**Comment by divdavem** [comment]
You can actually retry nearly same command line as the one you mentioned in this issue (`@latest` always points to the latest release in npm):
```
npx @amadeus-it-group/protractor-to-playwright@latest --src=D:\Automation_Repository\ui-platform-automation --dst='D:\conversion' validateAttributeMessage-po.js
```
Note that if you want to convert `it(...)` into `test.step(...)` instead of the default `test(...)`, you have to specify `--test=step` in the command line (and not just `step`).

**Comment by meghanagandhi-rs** [comment]
> You can actually retry nearly same command line as the one you mentioned in this issue (`@latest` always points to the latest release in npm):
> 
> ```
> npx @amadeus-it-group/protractor-to-playwright@latest --src=D:\Automation_Repository\ui-platform-automation --dst='D:\conversion' validateAttributeMessage-po.js
> ```
> 
> Note that if you want to convert `it(...)` into `test.step(...)` instead of the default `test(...)`, you have to specify `--test=step` in the command line (and not just `step`).

Thanks for explanations, I will try tomorrow and update you. :-)

**Comment by meghanagandhi-rs** [comment]
> You can actually retry nearly same command line as the one you mentioned in this issue (`@latest` always points to the latest release in npm):
> 
> ```
> npx @amadeus-it-group/protractor-to-playwright@latest --src=D:\Automation_Repository\ui-platform-automation --dst='D:\conversion' validateAttributeMessage-po.js
> ```
> 
> Note that if you want to convert `it(...)` into `test.step(...)` instead of the default `test(...)`, you have to specify `--test=step` in the command line (and not just `step`).

Hi Guys, 

Today, I run the same command and this time I have entered --test=step as well, still it is showing zero transformations. please check below :

PS D:\Playrightconversions\protractor-to-playwright> npx @amadeus-it-group/protractor-to-playwright@latest --src=D:\Automation_Repository\ui-platform-automation --dst='D:\conversion' validateAttributeMessage-po.js --test=step

Need to install the following packages:
  @amadeus-it-group/protractor-to-playwright@latest
Ok to proceed? (y) y
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.      
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Start migration
Apply 0 transformations
Migration finished
