### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by bboycs** [AmadeusITGroup/protractor-to-playwright#45]
Apply 20370 transformations
Applying changes █████████████████████████░░░░░░░░░░░░░░░ | 62% | 12697/20370 | checkbox.spec.js
<--- Last few GCs --->

[33188:000001FB4A0B98F0]   728339 ms: Mark-sweep 1832.5 (1899.5) -> 1832.5 (1856.3) MB, 713.2 / 0.0 ms  (average mu = 0.517, current mu = 0.000) last resort GC in old space requested
[33188:000001FB4A0B98F0]   728888 ms: Mark-sweep 1832.5 (1856.3) -> 1832.3 (1856.3) MB, 549.7 / 0.0 ms  (average mu = 0.360, current mu = 0.000) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF7FB0EB3BD]
Security context: 0x031529c008d1 <JSObject>
    1: set [0000031529C06691](this=0x03a9e6229721 <Map map = 00000349BDF00F29>,0x00bdaeb59ba1 <IdentifierObject map = 000001EFA9FF1A89>,0x024fc5f98c39 <Node map = 00000292EFDB93C9>)
    2: handleNode [00000368CD361651] [C:\Users\user\AppData\Roaming\npm-cache\_npx\33188\node_modules\@amadeus-it-group\protractor-to-playwright\node_modules\ts-morph\dist\ts-m...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 00007FF7FA4D5EBF napi_wrap+114095
 2: 00007FF7FA480B46 v8::base::CPU::has_sse+66998
 3: 00007FF7FA481946 v8::base::CPU::has_sse+70582
 4: 00007FF7FAC96E4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7FAC7EF21 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF7FAB4B18C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7FAB46E59 v8::internal::Heap::AddRetainedMap+2713
 8: 00007FF7FAB681DB v8::internal::Factory::NewFixedArrayWithFiller+107
 9: 00007FF7FAB61067 v8::internal::Factory::InternalizeString<unsigned short>+471
10: 00007FF7FA99D82B v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::Allocate+123
11: 00007FF7FA99F97B v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::Rehash+59
12: 00007FF7FA99E90A v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::EnsureGrowable+90
13: 00007FF7FA8E9C22 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+114882
14: 00007FF7FB0EB3BD v8::internal::SetupIsolateDelegate::SetupHeap+546637
15: 00007FF7FB0B001A v8::internal::SetupIsolateDelegate::SetupHeap+304042
16: 000001A421DC2D57

**Comment by divdavem** [comment]
@bboycs Thank you for reporting this issue. I have integrated a small change (#46) that may help using less memory. Please try again with the just released 1.3.2 version.
To avoid using too much memory, you could also run protractor-to-playwright multiple times on a reduced number of files. Also, please make sure you use the latest node.js version.
Do not hesitate to re-open this issue if it still does not work for you, but please include all the details so that we can reproduce the issue.
