### ISSUE TITLE
Mention Rayrun migration tool

### ISSUE THREAD

**Issue by lucgagan** [AmadeusITGroup/protractor-to-playwright#58]
https://ray.run/tools/protractor-to-playwright

It performs migration from Protractor to Playwright using LLMs.

I wrote a prompt that includes examples written both in Protractor and Playwright.

I found that while it is slower, it better handles some of the edge cases.

**Comment by fbasso** [comment]
Thanks for your suggestion. 

Unfortunately, the drawback of this tool is given by the note : 

> Unlike other tools you will find on this website, this tool sends data to the server. This is because the conversion is done using AI that is not available in the browser.

Which is a stopper for a lot of companies.

The second point is that you have to enter the code one by one (if I well understand), whereas the whole conversion is done  for the full project with [protractor-to-playwright ](protractor-to-playwright )
